/* exercice.c generated by valac 0.56.18, the Vala compiler
 * generated from exercice.vala, do not modify */

#include <gio/gio.h>
#include <glib.h>
#include <stdio.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

typedef struct _GomTestData GomTestData;

#define GOM_TYPE_TOTEM (gom_totem_get_type ())
#define GOM_TOTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GOM_TYPE_TOTEM, GomTotem))
#define GOM_TOTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GOM_TYPE_TOTEM, GomTotemClass))
#define GOM_IS_TOTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GOM_TYPE_TOTEM))
#define GOM_IS_TOTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GOM_TYPE_TOTEM))
#define GOM_TOTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GOM_TYPE_TOTEM, GomTotemClass))

typedef struct _GomTotem GomTotem;
typedef struct _GomTotemClass GomTotemClass;
typedef struct _GomTotemPrivate GomTotemPrivate;
enum  {
	GOM_TOTEM_0_PROPERTY,
	GOM_TOTEM_TR_PROPERTY,
	GOM_TOTEM_NUM_PROPERTIES
};
static GParamSpec* gom_totem_properties[GOM_TOTEM_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _GomTotemDeleteAsyncData GomTotemDeleteAsyncData;
typedef gboolean (*GomRepositoryMigrator) (guint version, gpointer user_data, GError** error);

struct _GomTestData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	gboolean result;
	FILE* _tmp0_;
};

struct _GomTotem {
	GObject parent_instance;
	GomTotemPrivate * priv;
};

struct _GomTotemClass {
	GObjectClass parent_class;
	gchar m2g[64];
};

struct _GomTotemPrivate {
	gchar* _tr;
};

struct _GomTotemDeleteAsyncData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	GomTotem* self;
	gboolean result;
};

static gint GomTotem_private_offset;
static gpointer gom_totem_parent_class = NULL;

static void gom_test_data_free (gpointer _data);
VALA_EXTERN void gom_test (GAsyncReadyCallback _callback_,
               gpointer _user_data_);
VALA_EXTERN gboolean gom_test_finish (GAsyncResult* _res_,
                          GError** error);
static gboolean gom_test_co (GomTestData* _data_);
VALA_EXTERN GType gom_totem_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GomTotem, g_object_unref)
VALA_EXTERN void gom_totem_calcul (void);
VALA_EXTERN gint gom_totem_get_toto (GomTotemClass* klass);
VALA_EXTERN gchar* gom_totem_set_toto (GomTotemClass* klass,
                           const gchar* m3g);
VALA_EXTERN GomTotem* gom_totem_new (const gchar* tr);
VALA_EXTERN GomTotem* gom_totem_construct (GType object_type,
                               const gchar* tr);
static void gom_totem_delete_async_data_free (gpointer _data);
VALA_EXTERN void gom_totem_delete_async (GomTotem* self,
                             GAsyncReadyCallback _callback_,
                             gpointer _user_data_);
VALA_EXTERN gboolean gom_totem_delete_finish (GomTotem* self,
                                  GAsyncResult* _res_,
                                  GError** error);
static gboolean gom_totem_delete_async_co (GomTotemDeleteAsyncData* _data_);
VALA_EXTERN gboolean gom_totem_save_sync (GomTotem* self,
                              GError** error);
VALA_EXTERN const gchar* gom_totem_get_tr (GomTotem* self);
static void gom_totem_set_tr (GomTotem* self,
                       const gchar* value);
static void gom_totem_finalize (GObject * obj);
static GType gom_totem_get_type_once (void);
static void _vala_gom_totem_get_property (GObject * object,
                                   guint property_id,
                                   GValue * value,
                                   GParamSpec * pspec);
static void _vala_gom_totem_set_property (GObject * object,
                                   guint property_id,
                                   const GValue * value,
                                   GParamSpec * pspec);
static void gom_main (void);

static void
gom_test_data_free (gpointer _data)
{
	GomTestData* _data_;
	_data_ = _data;
	g_slice_free (GomTestData, _data_);
}

void
gom_test (GAsyncReadyCallback _callback_,
          gpointer _user_data_)
{
	GomTestData* _data_;
	_data_ = g_slice_new0 (GomTestData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, gom_test_data_free);
	gom_test_co (_data_);
}

gboolean
gom_test_finish (GAsyncResult* _res_,
                 GError** error)
{
	gboolean result;
	GomTestData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), error);
	if (NULL == _data_) {
		gboolean _tmp0_ = FALSE;
		return _tmp0_;
	}
	result = _data_->result;
	return result;
}

static gboolean
gom_test_co (GomTestData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = stdout;
	fprintf (_data_->_tmp0_, "hello world\n");
	_data_->result = TRUE;
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static inline gpointer
gom_totem_get_instance_private (GomTotem* self)
{
	return G_STRUCT_MEMBER_P (self, GomTotem_private_offset);
}

void
gom_totem_calcul (void)
{
	gint a = 0;
	a = 0;
}

gint
gom_totem_get_toto (GomTotemClass* klass)
{
	gint result;
	klass->m2g[0] = '7';
	result = 4;
	return result;
}

gchar*
gom_totem_set_toto (GomTotemClass* klass,
                    const gchar* m3g)
{
	gchar* _tmp0_;
	gchar* result;
	g_return_val_if_fail (m3g != NULL, NULL);
	_tmp0_ = g_strdup (m3g);
	result = _tmp0_;
	return result;
}

GomTotem*
gom_totem_construct (GType object_type,
                     const gchar* tr)
{
	GomTotem * self = NULL;
	g_return_val_if_fail (tr != NULL, NULL);
	self = (GomTotem*) g_object_new (object_type, "tr", tr, NULL);
	return self;
}

GomTotem*
gom_totem_new (const gchar* tr)
{
	return gom_totem_construct (GOM_TYPE_TOTEM, tr);
}

static void
gom_totem_delete_async_data_free (gpointer _data)
{
	GomTotemDeleteAsyncData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (GomTotemDeleteAsyncData, _data_);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
gom_totem_delete_async (GomTotem* self,
                        GAsyncReadyCallback _callback_,
                        gpointer _user_data_)
{
	GomTotemDeleteAsyncData* _data_;
	GomTotem* _tmp0_;
	g_return_if_fail (self != NULL);
	_data_ = g_slice_new0 (GomTotemDeleteAsyncData);
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, gom_totem_delete_async_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	gom_totem_delete_async_co (_data_);
}

gboolean
gom_totem_delete_finish (GomTotem* self,
                         GAsyncResult* _res_,
                         GError** error)
{
	gboolean result;
	GomTotemDeleteAsyncData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), error);
	if (NULL == _data_) {
		gboolean _tmp0_ = FALSE;
		return _tmp0_;
	}
	result = _data_->result;
	return result;
}

static gboolean
gom_totem_delete_async_co (GomTotemDeleteAsyncData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->result = TRUE;
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

gboolean
gom_totem_save_sync (GomTotem* self,
                     GError** error)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = TRUE;
	return result;
}

const gchar*
gom_totem_get_tr (GomTotem* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tr;
	result = _tmp0_;
	return result;
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static void
gom_totem_set_tr (GomTotem* self,
                  const gchar* value)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = string_to_string (value);
	_tmp1_ = g_strconcat (" copy-call ", _tmp0_, NULL);
	_g_free0 (self->priv->_tr);
	self->priv->_tr = _tmp1_;
	g_object_notify_by_pspec ((GObject *) self, gom_totem_properties[GOM_TOTEM_TR_PROPERTY]);
}

static void
gom_totem_class_init (GomTotemClass * klass,
                      gpointer klass_data)
{
	gom_totem_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &GomTotem_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_gom_totem_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_gom_totem_set_property;
	G_OBJECT_CLASS (klass)->finalize = gom_totem_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GOM_TOTEM_TR_PROPERTY, gom_totem_properties[GOM_TOTEM_TR_PROPERTY] = g_param_spec_string ("tr", "tr", "tr", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
}

static void
gom_totem_instance_init (GomTotem * self,
                         gpointer klass)
{
	self->priv = gom_totem_get_instance_private (self);
}

static void
gom_totem_finalize (GObject * obj)
{
	GomTotem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GOM_TYPE_TOTEM, GomTotem);
	_g_free0 (self->priv->_tr);
	G_OBJECT_CLASS (gom_totem_parent_class)->finalize (obj);
}

static GType
gom_totem_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GomTotemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gom_totem_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GomTotem), 0, (GInstanceInitFunc) gom_totem_instance_init, NULL };
	GType gom_totem_type_id;
	gom_totem_type_id = g_type_register_static (G_TYPE_OBJECT, "GomTotem", &g_define_type_info, 0);
	GomTotem_private_offset = g_type_add_instance_private (gom_totem_type_id, sizeof (GomTotemPrivate));
	return gom_totem_type_id;
}

GType
gom_totem_get_type (void)
{
	static volatile gsize gom_totem_type_id__once = 0;
	if (g_once_init_enter (&gom_totem_type_id__once)) {
		GType gom_totem_type_id;
		gom_totem_type_id = gom_totem_get_type_once ();
		g_once_init_leave (&gom_totem_type_id__once, gom_totem_type_id);
	}
	return gom_totem_type_id__once;
}

static void
_vala_gom_totem_get_property (GObject * object,
                              guint property_id,
                              GValue * value,
                              GParamSpec * pspec)
{
	GomTotem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GOM_TYPE_TOTEM, GomTotem);
	switch (property_id) {
		case GOM_TOTEM_TR_PROPERTY:
		g_value_set_string (value, gom_totem_get_tr (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_gom_totem_set_property (GObject * object,
                              guint property_id,
                              const GValue * value,
                              GParamSpec * pspec)
{
	GomTotem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GOM_TYPE_TOTEM, GomTotem);
	switch (property_id) {
		case GOM_TOTEM_TR_PROPERTY:
		gom_totem_set_tr (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static guint8*
string_get_data (const gchar* self,
                 gint* result_length1)
{
	guint8* result;
	guint8* res = NULL;
	gint res_length1;
	gint _res_size_;
	gint _tmp0_;
	gint _tmp1_;
	guint8* _tmp2_;
	gint _tmp2__length1;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res;
	_tmp2__length1 = res_length1;
	if (result_length1) {
		*result_length1 = _tmp2__length1;
	}
	result = _tmp2_;
	return result;
}

static void
gom_main (void)
{
	GomTotem* t = NULL;
	GomTotem* _tmp0_;
	FILE* _tmp1_;
	FILE* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	guint8* _tmp7_;
	gint _tmp7__length1;
	gint _tmp8_ = 0;
	guint8* _tmp9_;
	gint _tmp9__length1;
	FILE* _tmp10_;
	const gchar* _tmp11_;
	const gchar* _tmp12_;
	FILE* _tmp13_;
	gchar* s = NULL;
	gchar* _tmp14_;
	FILE* _tmp15_;
	const gchar* _tmp16_;
	gchar* _tmp17_;
	FILE* _tmp18_;
	const gchar* _tmp19_;
	_tmp0_ = gom_totem_new ("banana");
	t = _tmp0_;
	_tmp1_ = stdout;
	fprintf (_tmp1_, "%d\n", gom_totem_get_toto (GOM_TOTEM_GET_CLASS (t)));
	_tmp2_ = stdout;
	_tmp3_ = gom_totem_get_tr (t);
	_tmp4_ = _tmp3_;
	fprintf (_tmp2_, "tr: %s\n", _tmp4_);
	_tmp5_ = gom_totem_set_toto (GOM_TOTEM_GET_CLASS (t), "789+fgh");
	_tmp6_ = _tmp5_;
	_tmp7_ = string_get_data (_tmp6_, &_tmp8_);
	_tmp7__length1 = _tmp8_;
	_tmp9_ = _tmp7_;
	_tmp9__length1 = _tmp7__length1;
	memcpy (GOM_TOTEM_GET_CLASS (t)->m2g, (gchar*) _tmp9_, 64 * sizeof (gchar));
	_g_free0 (_tmp6_);
	_tmp10_ = stdout;
	_tmp11_ = gom_totem_get_tr (t);
	_tmp12_ = _tmp11_;
	fprintf (_tmp10_, "tr: %s\n", _tmp12_);
	_tmp13_ = stdout;
	fprintf (_tmp13_, "tr: %s\n", (const gchar*) GOM_TOTEM_GET_CLASS (t)->m2g);
	_tmp14_ = g_strdup ("bonjour");
	_g_free0 (s);
	s = _tmp14_;
	_tmp15_ = stdout;
	_tmp16_ = s;
	fprintf (_tmp15_, "%s\n", _tmp16_);
	_tmp17_ = g_strdup ("coco");
	_g_free0 (s);
	s = _tmp17_;
	_tmp18_ = stdout;
	_tmp19_ = s;
	fprintf (_tmp18_, "%s\n", _tmp19_);
	_g_free0 (s);
	_g_object_unref0 (t);
}

int
main (int argc,
      char ** argv)
{
	gom_main ();
	return 0;
}

