/* main.c generated by valac 0.56.18, the Vala compiler
 * generated from main.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include "gom-adapter.h"
#include "gom-repository.h"
#include <glib-object.h>
#include "gom-error.h"
#include <stdio.h>
#include "gom-resource.h"

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define YK_TYPE_MONITOR (yk_monitor_get_type ())
#define YK_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YK_TYPE_MONITOR, YkMonitor))
#define YK_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YK_TYPE_MONITOR, YkMonitorClass))
#define YK_IS_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YK_TYPE_MONITOR))
#define YK_IS_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YK_TYPE_MONITOR))
#define YK_MONITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YK_TYPE_MONITOR, YkMonitorClass))

typedef struct _YkMonitor YkMonitor;
typedef struct _YkMonitorClass YkMonitorClass;
typedef struct _YkMonitorPrivate YkMonitorPrivate;
typedef struct _YkMonitorClassPrivate YkMonitorClassPrivate;
enum  {
	YK_MONITOR_0_PROPERTY,
	YK_MONITOR_ID_PROPERTY,
	YK_MONITOR_NAME_PROPERTY,
	YK_MONITOR_USERNAME_PROPERTY,
	YK_MONITOR_PASSWORD_PROPERTY,
	YK_MONITOR_MID_PROPERTY,
	YK_MONITOR_CONNECTIC_PROPERTY,
	YK_MONITOR_DESCRIPTION_PROPERTY,
	YK_MONITOR_VOLUME_PROPERTY,
	YK_MONITOR_NUM_PROPERTIES
};
static GParamSpec* yk_monitor_properties[YK_MONITOR_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

#define YK_TYPE_TESLA (yk_tesla_get_type ())
#define YK_TESLA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YK_TYPE_TESLA, YkTesla))
#define YK_TESLA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YK_TYPE_TESLA, YkTeslaClass))
#define YK_IS_TESLA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YK_TYPE_TESLA))
#define YK_IS_TESLA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YK_TYPE_TESLA))
#define YK_TESLA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YK_TYPE_TESLA, YkTeslaClass))

typedef struct _YkTesla YkTesla;
typedef struct _YkTeslaClass YkTeslaClass;
typedef struct _YkTeslaPrivate YkTeslaPrivate;
typedef struct _YkTeslaClassPrivate YkTeslaClassPrivate;
enum  {
	YK_TESLA_0_PROPERTY,
	YK_TESLA_KOKO_PROPERTY,
	YK_TESLA_SURNAME_PROPERTY,
	YK_TESLA_NUM_PROPERTIES
};
static GParamSpec* yk_tesla_properties[YK_TESLA_NUM_PROPERTIES];

struct _YkMonitor {
	GomResource parent_instance;
	YkMonitorPrivate * priv;
};

struct _YkMonitorClass {
	GomResourceClass parent_class;
};

struct _YkMonitorPrivate {
	gint64 _id;
	gchar* _name;
	gchar* _username;
	gchar* _password;
	gchar* _mid;
	gchar* _connectic;
	gchar* _description;
	gint _volume;
};

struct _YkMonitorClassPrivate {
	gboolean _init;
};

struct _YkTesla {
	YkMonitor parent_instance;
	YkTeslaPrivate * priv;
};

struct _YkTeslaClass {
	YkMonitorClass parent_class;
};

struct _YkTeslaPrivate {
	gint64 _koko;
	gchar* _surname;
};

struct _YkTeslaClassPrivate {
	gboolean _init;
};

static gint YkMonitor_private_offset;
static gpointer yk_monitor_parent_class = NULL;
static gint YkTesla_private_offset;
static gpointer yk_tesla_parent_class = NULL;

VALA_EXTERN GomRepository* yk_easy_open_sync (const gchar* db_uri,
                                  GomAdapter** adapter,
                                  GError** error);
VALA_EXTERN GType yk_monitor_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (YkMonitor, g_object_unref)
#define YK_MONITOR_GET_CLASS_PRIVATE(klass) (G_TYPE_CLASS_GET_PRIVATE (klass, YK_TYPE_MONITOR, YkMonitorClassPrivate))
VALA_EXTERN YkMonitor* yk_monitor_new (void);
VALA_EXTERN YkMonitor* yk_monitor_construct (GType object_type);
VALA_EXTERN gint64 yk_monitor_get_id (YkMonitor* self);
VALA_EXTERN void yk_monitor_set_id (YkMonitor* self,
                        gint64 value);
VALA_EXTERN const gchar* yk_monitor_get_name (YkMonitor* self);
VALA_EXTERN void yk_monitor_set_name (YkMonitor* self,
                          const gchar* value);
VALA_EXTERN const gchar* yk_monitor_get_username (YkMonitor* self);
VALA_EXTERN void yk_monitor_set_username (YkMonitor* self,
                              const gchar* value);
VALA_EXTERN const gchar* yk_monitor_get_password (YkMonitor* self);
VALA_EXTERN void yk_monitor_set_password (YkMonitor* self,
                              const gchar* value);
VALA_EXTERN const gchar* yk_monitor_get_mid (YkMonitor* self);
VALA_EXTERN void yk_monitor_set_mid (YkMonitor* self,
                         const gchar* value);
VALA_EXTERN const gchar* yk_monitor_get_connectic (YkMonitor* self);
VALA_EXTERN void yk_monitor_set_connectic (YkMonitor* self,
                               const gchar* value);
VALA_EXTERN const gchar* yk_monitor_get_description (YkMonitor* self);
VALA_EXTERN void yk_monitor_set_description (YkMonitor* self,
                                 const gchar* value);
VALA_EXTERN gint yk_monitor_get_volume (YkMonitor* self);
VALA_EXTERN void yk_monitor_set_volume (YkMonitor* self,
                            gint value);
static GObject * yk_monitor_constructor (GType type,
                                  guint n_construct_properties,
                                  GObjectConstructParam * construct_properties);
static void yk_monitor_finalize (GObject * obj);
static GType yk_monitor_get_type_once (void);
static void _vala_yk_monitor_get_property (GObject * object,
                                    guint property_id,
                                    GValue * value,
                                    GParamSpec * pspec);
static void _vala_yk_monitor_set_property (GObject * object,
                                    guint property_id,
                                    const GValue * value,
                                    GParamSpec * pspec);
VALA_EXTERN GType yk_tesla_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (YkTesla, g_object_unref)
#define YK_TESLA_GET_CLASS_PRIVATE(klass) (G_TYPE_CLASS_GET_PRIVATE (klass, YK_TYPE_TESLA, YkTeslaClassPrivate))
VALA_EXTERN YkTesla* yk_tesla_new (void);
VALA_EXTERN YkTesla* yk_tesla_construct (GType object_type);
VALA_EXTERN gint64 yk_tesla_get_koko (YkTesla* self);
VALA_EXTERN void yk_tesla_set_koko (YkTesla* self,
                        gint64 value);
VALA_EXTERN const gchar* yk_tesla_get_surname (YkTesla* self);
VALA_EXTERN void yk_tesla_set_surname (YkTesla* self,
                           const gchar* value);
static GObject * yk_tesla_constructor (GType type,
                                guint n_construct_properties,
                                GObjectConstructParam * construct_properties);
static void yk_tesla_finalize (GObject * obj);
static GType yk_tesla_get_type_once (void);
static void _vala_yk_tesla_get_property (GObject * object,
                                  guint property_id,
                                  GValue * value,
                                  GParamSpec * pspec);
static void _vala_yk_tesla_set_property (GObject * object,
                                  guint property_id,
                                  const GValue * value,
                                  GParamSpec * pspec);
static void yk_main (void);

static GomAdapter*
gom_adapter_construct (GType object_type)
{
	GomAdapter * self = NULL;
	self = (GomAdapter*) g_object_new (object_type, NULL);
	return self;
}

static gpointer
_g_error_copy0 (gpointer self)
{
	return self ? g_error_copy (self) : NULL;
}

GomRepository*
yk_easy_open_sync (const gchar* db_uri,
                   GomAdapter** adapter,
                   GError** error)
{
	GomAdapter* _vala_adapter = NULL;
	GomAdapter* _tmp0_;
	GomAdapter* _tmp9_;
	GomRepository* _tmp10_;
	GError* _inner_error0_ = NULL;
	GomRepository* result;
	g_return_val_if_fail (db_uri != NULL, NULL);
	_tmp0_ = gom_adapter_new ();
	_g_object_unref0 (_vala_adapter);
	_vala_adapter = _tmp0_;
	{
		GomAdapter* _tmp1_;
		_tmp1_ = _vala_adapter;
		gom_adapter_open_sync (_tmp1_, db_uri, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == GOM_ERROR) {
				goto __catch0_gom_error;
			}
			goto __finally0;
		}
	}
	goto __finally0;
	__catch0_gom_error:
	{
		GError* e = NULL;
		GError* _tmp2_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp2_ = e;
		if (g_error_matches (_tmp2_, GOM_ERROR, GOM_ERROR_ADAPTER_OPEN)) {
			FILE* _tmp3_;
			GError* _tmp4_;
			const gchar* _tmp5_;
			GomAdapter* _tmp6_;
			GError* _tmp7_;
			GError* _tmp8_;
			_tmp3_ = stdout;
			_tmp4_ = e;
			_tmp5_ = _tmp4_->message;
			fprintf (_tmp3_, "Error: %s\n", _tmp5_);
			_tmp6_ = _vala_adapter;
			gom_adapter_close_sync (_tmp6_, &_inner_error0_);
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_error_free0 (e);
				goto __finally0;
			}
			_tmp7_ = e;
			_tmp8_ = _g_error_copy0 (_tmp7_);
			_inner_error0_ = _tmp8_;
			_g_error_free0 (e);
			goto __finally0;
		}
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		_g_object_unref0 (_vala_adapter);
		return NULL;
	}
	_tmp9_ = _vala_adapter;
	_tmp10_ = gom_repository_new (_tmp9_);
	result = _tmp10_;
	if (adapter) {
		*adapter = _vala_adapter;
	} else {
		_g_object_unref0 (_vala_adapter);
	}
	return result;
}

static inline gpointer
yk_monitor_get_instance_private (YkMonitor* self)
{
	return G_STRUCT_MEMBER_P (self, YkMonitor_private_offset);
}

YkMonitor*
yk_monitor_construct (GType object_type)
{
	YkMonitor * self = NULL;
	self = (YkMonitor*) g_object_new (object_type, NULL);
	return self;
}

YkMonitor*
yk_monitor_new (void)
{
	return yk_monitor_construct (YK_TYPE_MONITOR);
}

gint64
yk_monitor_get_id (YkMonitor* self)
{
	gint64 result;
	g_return_val_if_fail (self != NULL, 0LL);
	result = self->priv->_id;
	return result;
}

void
yk_monitor_set_id (YkMonitor* self,
                   gint64 value)
{
	gint64 old_value;
	g_return_if_fail (self != NULL);
	old_value = yk_monitor_get_id (self);
	if (old_value != value) {
		self->priv->_id = value;
		g_object_notify_by_pspec ((GObject *) self, yk_monitor_properties[YK_MONITOR_ID_PROPERTY]);
	}
}

const gchar*
yk_monitor_get_name (YkMonitor* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}

void
yk_monitor_set_name (YkMonitor* self,
                     const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = yk_monitor_get_name (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_name);
		self->priv->_name = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, yk_monitor_properties[YK_MONITOR_NAME_PROPERTY]);
	}
}

const gchar*
yk_monitor_get_username (YkMonitor* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_username;
	result = _tmp0_;
	return result;
}

void
yk_monitor_set_username (YkMonitor* self,
                         const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = yk_monitor_get_username (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_username);
		self->priv->_username = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, yk_monitor_properties[YK_MONITOR_USERNAME_PROPERTY]);
	}
}

const gchar*
yk_monitor_get_password (YkMonitor* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_password;
	result = _tmp0_;
	return result;
}

void
yk_monitor_set_password (YkMonitor* self,
                         const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = yk_monitor_get_password (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_password);
		self->priv->_password = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, yk_monitor_properties[YK_MONITOR_PASSWORD_PROPERTY]);
	}
}

const gchar*
yk_monitor_get_mid (YkMonitor* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_mid;
	result = _tmp0_;
	return result;
}

void
yk_monitor_set_mid (YkMonitor* self,
                    const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = yk_monitor_get_mid (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_mid);
		self->priv->_mid = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, yk_monitor_properties[YK_MONITOR_MID_PROPERTY]);
	}
}

const gchar*
yk_monitor_get_connectic (YkMonitor* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_connectic;
	result = _tmp0_;
	return result;
}

void
yk_monitor_set_connectic (YkMonitor* self,
                          const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = yk_monitor_get_connectic (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_connectic);
		self->priv->_connectic = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, yk_monitor_properties[YK_MONITOR_CONNECTIC_PROPERTY]);
	}
}

const gchar*
yk_monitor_get_description (YkMonitor* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_description;
	result = _tmp0_;
	return result;
}

void
yk_monitor_set_description (YkMonitor* self,
                            const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = yk_monitor_get_description (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_description);
		self->priv->_description = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, yk_monitor_properties[YK_MONITOR_DESCRIPTION_PROPERTY]);
	}
}

gint
yk_monitor_get_volume (YkMonitor* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_volume;
	return result;
}

void
yk_monitor_set_volume (YkMonitor* self,
                       gint value)
{
	gint old_value;
	g_return_if_fail (self != NULL);
	old_value = yk_monitor_get_volume (self);
	if (old_value != value) {
		self->priv->_volume = value;
		g_object_notify_by_pspec ((GObject *) self, yk_monitor_properties[YK_MONITOR_VOLUME_PROPERTY]);
	}
}

static GObject *
yk_monitor_constructor (GType type,
                        guint n_construct_properties,
                        GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	YkMonitor * self;
	parent_class = G_OBJECT_CLASS (yk_monitor_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YK_TYPE_MONITOR, YkMonitor);
	if (YK_MONITOR_GET_CLASS_PRIVATE (YK_MONITOR_GET_CLASS (self))->_init) {
		return obj;
	}
	gom_resource_class_set_table (G_TYPE_INSTANCE_GET_CLASS (self, gom_resource_get_type (), GomResourceClass), "monitor");
	gom_resource_class_set_primary_key (G_TYPE_INSTANCE_GET_CLASS (self, gom_resource_get_type (), GomResourceClass), "id");
	gom_resource_class_set_unique (G_TYPE_INSTANCE_GET_CLASS (self, gom_resource_get_type (), GomResourceClass), "name");
	gom_resource_class_set_unique (G_TYPE_INSTANCE_GET_CLASS (self, gom_resource_get_type (), GomResourceClass), "mid");
	gom_resource_class_set_notnull (G_TYPE_INSTANCE_GET_CLASS (self, gom_resource_get_type (), GomResourceClass), "name");
	gom_resource_class_set_notnull (G_TYPE_INSTANCE_GET_CLASS (self, gom_resource_get_type (), GomResourceClass), "mid");
	gom_resource_class_set_notnull (G_TYPE_INSTANCE_GET_CLASS (self, gom_resource_get_type (), GomResourceClass), "password");
	gom_resource_class_set_notnull (G_TYPE_INSTANCE_GET_CLASS (self, gom_resource_get_type (), GomResourceClass), "username");
	YK_MONITOR_GET_CLASS_PRIVATE (YK_MONITOR_GET_CLASS (self))->_init = TRUE;
	return obj;
}

static void
yk_monitor_class_init (YkMonitorClass * klass,
                       gpointer klass_data)
{
	yk_monitor_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &YkMonitor_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_yk_monitor_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_yk_monitor_set_property;
	G_OBJECT_CLASS (klass)->constructor = yk_monitor_constructor;
	G_OBJECT_CLASS (klass)->finalize = yk_monitor_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), YK_MONITOR_ID_PROPERTY, yk_monitor_properties[YK_MONITOR_ID_PROPERTY] = g_param_spec_int64 ("id", "id", "id", G_MININT64, G_MAXINT64, (gint64) 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YK_MONITOR_NAME_PROPERTY, yk_monitor_properties[YK_MONITOR_NAME_PROPERTY] = g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YK_MONITOR_USERNAME_PROPERTY, yk_monitor_properties[YK_MONITOR_USERNAME_PROPERTY] = g_param_spec_string ("username", "username", "username", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YK_MONITOR_PASSWORD_PROPERTY, yk_monitor_properties[YK_MONITOR_PASSWORD_PROPERTY] = g_param_spec_string ("password", "password", "password", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YK_MONITOR_MID_PROPERTY, yk_monitor_properties[YK_MONITOR_MID_PROPERTY] = g_param_spec_string ("mid", "mid", "mid", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YK_MONITOR_CONNECTIC_PROPERTY, yk_monitor_properties[YK_MONITOR_CONNECTIC_PROPERTY] = g_param_spec_string ("connectic", "connectic", "connectic", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YK_MONITOR_DESCRIPTION_PROPERTY, yk_monitor_properties[YK_MONITOR_DESCRIPTION_PROPERTY] = g_param_spec_string ("description", "description", "description", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YK_MONITOR_VOLUME_PROPERTY, yk_monitor_properties[YK_MONITOR_VOLUME_PROPERTY] = g_param_spec_int ("volume", "volume", "volume", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	YK_MONITOR_GET_CLASS_PRIVATE (klass)->_init = FALSE;
}

static void
yk_monitor_instance_init (YkMonitor * self,
                          gpointer klass)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	self->priv = yk_monitor_get_instance_private (self);
	self->priv->_id = (gint64) 0;
	self->priv->_name = NULL;
	_tmp0_ = g_strdup ("admin");
	self->priv->_username = _tmp0_;
	_tmp1_ = g_strdup ("admin");
	self->priv->_password = _tmp1_;
	self->priv->_mid = NULL;
	self->priv->_connectic = NULL;
	self->priv->_description = NULL;
	self->priv->_volume = 0;
}

static void
yk_monitor_finalize (GObject * obj)
{
	YkMonitor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YK_TYPE_MONITOR, YkMonitor);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_username);
	_g_free0 (self->priv->_password);
	_g_free0 (self->priv->_mid);
	_g_free0 (self->priv->_connectic);
	_g_free0 (self->priv->_description);
	G_OBJECT_CLASS (yk_monitor_parent_class)->finalize (obj);
}

static GType
yk_monitor_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (YkMonitorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yk_monitor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (YkMonitor), 0, (GInstanceInitFunc) yk_monitor_instance_init, NULL };
	GType yk_monitor_type_id;
	yk_monitor_type_id = g_type_register_static (gom_resource_get_type (), "YkMonitor", &g_define_type_info, 0);
	g_type_add_class_private (yk_monitor_type_id, sizeof (YkMonitorClassPrivate));
	YkMonitor_private_offset = g_type_add_instance_private (yk_monitor_type_id, sizeof (YkMonitorPrivate));
	return yk_monitor_type_id;
}

GType
yk_monitor_get_type (void)
{
	static volatile gsize yk_monitor_type_id__once = 0;
	if (g_once_init_enter (&yk_monitor_type_id__once)) {
		GType yk_monitor_type_id;
		yk_monitor_type_id = yk_monitor_get_type_once ();
		g_once_init_leave (&yk_monitor_type_id__once, yk_monitor_type_id);
	}
	return yk_monitor_type_id__once;
}

static void
_vala_yk_monitor_get_property (GObject * object,
                               guint property_id,
                               GValue * value,
                               GParamSpec * pspec)
{
	YkMonitor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YK_TYPE_MONITOR, YkMonitor);
	switch (property_id) {
		case YK_MONITOR_ID_PROPERTY:
		g_value_set_int64 (value, yk_monitor_get_id (self));
		break;
		case YK_MONITOR_NAME_PROPERTY:
		g_value_set_string (value, yk_monitor_get_name (self));
		break;
		case YK_MONITOR_USERNAME_PROPERTY:
		g_value_set_string (value, yk_monitor_get_username (self));
		break;
		case YK_MONITOR_PASSWORD_PROPERTY:
		g_value_set_string (value, yk_monitor_get_password (self));
		break;
		case YK_MONITOR_MID_PROPERTY:
		g_value_set_string (value, yk_monitor_get_mid (self));
		break;
		case YK_MONITOR_CONNECTIC_PROPERTY:
		g_value_set_string (value, yk_monitor_get_connectic (self));
		break;
		case YK_MONITOR_DESCRIPTION_PROPERTY:
		g_value_set_string (value, yk_monitor_get_description (self));
		break;
		case YK_MONITOR_VOLUME_PROPERTY:
		g_value_set_int (value, yk_monitor_get_volume (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_yk_monitor_set_property (GObject * object,
                               guint property_id,
                               const GValue * value,
                               GParamSpec * pspec)
{
	YkMonitor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YK_TYPE_MONITOR, YkMonitor);
	switch (property_id) {
		case YK_MONITOR_ID_PROPERTY:
		yk_monitor_set_id (self, g_value_get_int64 (value));
		break;
		case YK_MONITOR_NAME_PROPERTY:
		yk_monitor_set_name (self, g_value_get_string (value));
		break;
		case YK_MONITOR_USERNAME_PROPERTY:
		yk_monitor_set_username (self, g_value_get_string (value));
		break;
		case YK_MONITOR_PASSWORD_PROPERTY:
		yk_monitor_set_password (self, g_value_get_string (value));
		break;
		case YK_MONITOR_MID_PROPERTY:
		yk_monitor_set_mid (self, g_value_get_string (value));
		break;
		case YK_MONITOR_CONNECTIC_PROPERTY:
		yk_monitor_set_connectic (self, g_value_get_string (value));
		break;
		case YK_MONITOR_DESCRIPTION_PROPERTY:
		yk_monitor_set_description (self, g_value_get_string (value));
		break;
		case YK_MONITOR_VOLUME_PROPERTY:
		yk_monitor_set_volume (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static inline gpointer
yk_tesla_get_instance_private (YkTesla* self)
{
	return G_STRUCT_MEMBER_P (self, YkTesla_private_offset);
}

YkTesla*
yk_tesla_construct (GType object_type)
{
	YkTesla * self = NULL;
	self = (YkTesla*) yk_monitor_construct (object_type);
	return self;
}

YkTesla*
yk_tesla_new (void)
{
	return yk_tesla_construct (YK_TYPE_TESLA);
}

gint64
yk_tesla_get_koko (YkTesla* self)
{
	gint64 result;
	g_return_val_if_fail (self != NULL, 0LL);
	result = self->priv->_koko;
	return result;
}

void
yk_tesla_set_koko (YkTesla* self,
                   gint64 value)
{
	gint64 old_value;
	g_return_if_fail (self != NULL);
	old_value = yk_tesla_get_koko (self);
	if (old_value != value) {
		self->priv->_koko = value;
		g_object_notify_by_pspec ((GObject *) self, yk_tesla_properties[YK_TESLA_KOKO_PROPERTY]);
	}
}

const gchar*
yk_tesla_get_surname (YkTesla* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_surname;
	result = _tmp0_;
	return result;
}

void
yk_tesla_set_surname (YkTesla* self,
                      const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = yk_tesla_get_surname (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_surname);
		self->priv->_surname = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, yk_tesla_properties[YK_TESLA_SURNAME_PROPERTY]);
	}
}

static GObject *
yk_tesla_constructor (GType type,
                      guint n_construct_properties,
                      GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	YkTesla * self;
	parent_class = G_OBJECT_CLASS (yk_tesla_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YK_TYPE_TESLA, YkTesla);
	if (YK_TESLA_GET_CLASS_PRIVATE (YK_TESLA_GET_CLASS (self))->_init) {
		return obj;
	}
	gom_resource_class_set_table (G_TYPE_INSTANCE_GET_CLASS (self, gom_resource_get_type (), GomResourceClass), "tesla");
	gom_resource_class_set_notnull (G_TYPE_INSTANCE_GET_CLASS (self, gom_resource_get_type (), GomResourceClass), "koko");
	gom_resource_class_set_notnull (G_TYPE_INSTANCE_GET_CLASS (self, gom_resource_get_type (), GomResourceClass), "surname");
	YK_TESLA_GET_CLASS_PRIVATE (YK_TESLA_GET_CLASS (self))->_init = TRUE;
	return obj;
}

static void
yk_tesla_class_init (YkTeslaClass * klass,
                     gpointer klass_data)
{
	yk_tesla_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &YkTesla_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_yk_tesla_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_yk_tesla_set_property;
	G_OBJECT_CLASS (klass)->constructor = yk_tesla_constructor;
	G_OBJECT_CLASS (klass)->finalize = yk_tesla_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), YK_TESLA_KOKO_PROPERTY, yk_tesla_properties[YK_TESLA_KOKO_PROPERTY] = g_param_spec_int64 ("koko", "koko", "koko", G_MININT64, G_MAXINT64, (gint64) 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YK_TESLA_SURNAME_PROPERTY, yk_tesla_properties[YK_TESLA_SURNAME_PROPERTY] = g_param_spec_string ("surname", "surname", "surname", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	YK_TESLA_GET_CLASS_PRIVATE (klass)->_init = FALSE;
}

static void
yk_tesla_instance_init (YkTesla * self,
                        gpointer klass)
{
	self->priv = yk_tesla_get_instance_private (self);
	self->priv->_koko = (gint64) 0;
	self->priv->_surname = NULL;
}

static void
yk_tesla_finalize (GObject * obj)
{
	YkTesla * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YK_TYPE_TESLA, YkTesla);
	_g_free0 (self->priv->_surname);
	G_OBJECT_CLASS (yk_tesla_parent_class)->finalize (obj);
}

static GType
yk_tesla_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (YkTeslaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yk_tesla_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (YkTesla), 0, (GInstanceInitFunc) yk_tesla_instance_init, NULL };
	GType yk_tesla_type_id;
	yk_tesla_type_id = g_type_register_static (YK_TYPE_MONITOR, "YkTesla", &g_define_type_info, 0);
	g_type_add_class_private (yk_tesla_type_id, sizeof (YkTeslaClassPrivate));
	YkTesla_private_offset = g_type_add_instance_private (yk_tesla_type_id, sizeof (YkTeslaPrivate));
	return yk_tesla_type_id;
}

GType
yk_tesla_get_type (void)
{
	static volatile gsize yk_tesla_type_id__once = 0;
	if (g_once_init_enter (&yk_tesla_type_id__once)) {
		GType yk_tesla_type_id;
		yk_tesla_type_id = yk_tesla_get_type_once ();
		g_once_init_leave (&yk_tesla_type_id__once, yk_tesla_type_id);
	}
	return yk_tesla_type_id__once;
}

static void
_vala_yk_tesla_get_property (GObject * object,
                             guint property_id,
                             GValue * value,
                             GParamSpec * pspec)
{
	YkTesla * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YK_TYPE_TESLA, YkTesla);
	switch (property_id) {
		case YK_TESLA_KOKO_PROPERTY:
		g_value_set_int64 (value, yk_tesla_get_koko (self));
		break;
		case YK_TESLA_SURNAME_PROPERTY:
		g_value_set_string (value, yk_tesla_get_surname (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_yk_tesla_set_property (GObject * object,
                             guint property_id,
                             const GValue * value,
                             GParamSpec * pspec)
{
	YkTesla * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YK_TYPE_TESLA, YkTesla);
	switch (property_id) {
		case YK_TESLA_KOKO_PROPERTY:
		yk_tesla_set_koko (self, g_value_get_int64 (value));
		break;
		case YK_TESLA_SURNAME_PROPERTY:
		yk_tesla_set_surname (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
yk_main (void)
{
	YkMonitor* monitor = NULL;
	YkMonitor* _tmp0_;
	YkTesla* tesla = NULL;
	YkTesla* _tmp1_;
	GList* ltypes = NULL;
	YkMonitor* _tmp2_;
	YkTesla* _tmp3_;
	GomAdapter* adapter = NULL;
	GomRepository* repo = NULL;
	GError* _inner_error0_ = NULL;
	_tmp0_ = yk_monitor_new ();
	monitor = _tmp0_;
	_tmp1_ = yk_tesla_new ();
	tesla = _tmp1_;
	ltypes = NULL;
	_tmp2_ = monitor;
	ltypes = g_list_append (ltypes, (gpointer) ((gintptr) G_TYPE_FROM_INSTANCE ((GObject*) _tmp2_)));
	_tmp3_ = tesla;
	ltypes = g_list_append (ltypes, (gpointer) ((gintptr) G_TYPE_FROM_INSTANCE ((GObject*) _tmp3_)));
	{
		GomRepository* _tmp4_ = NULL;
		GomAdapter* _tmp5_ = NULL;
		GomRepository* _tmp6_;
		GomRepository* _tmp7_;
		GomRepository* _tmp8_;
		GList* _tmp9_;
		GomAdapter* _tmp10_;
		_tmp6_ = yk_easy_open_sync ("/home/nar6du14/Projects/vala/gom/test0/test.db", &_tmp5_, &_inner_error0_);
		_g_object_unref0 (adapter);
		adapter = _tmp5_;
		_tmp4_ = _tmp6_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == GOM_ERROR) {
				goto __catch0_gom_error;
			}
			goto __finally0;
		}
		_tmp7_ = _tmp4_;
		_tmp4_ = NULL;
		_g_object_unref0 (repo);
		repo = _tmp7_;
		_tmp8_ = repo;
		_tmp9_ = ltypes;
		ltypes = NULL;
		gom_repository_automatic_migrate_sync (_tmp8_, (guint) 1, _tmp9_, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (_tmp4_);
			if (_inner_error0_->domain == GOM_ERROR) {
				goto __catch0_gom_error;
			}
			goto __finally0;
		}
		_tmp10_ = adapter;
		gom_adapter_close_sync (_tmp10_, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (_tmp4_);
			if (_inner_error0_->domain == GOM_ERROR) {
				goto __catch0_gom_error;
			}
			goto __finally0;
		}
		_g_object_unref0 (_tmp4_);
	}
	goto __finally0;
	__catch0_gom_error:
	{
		GError* e = NULL;
		FILE* _tmp11_;
		GError* _tmp12_;
		const gchar* _tmp13_;
		GomRepository* _tmp14_ = NULL;
		GomAdapter* _tmp15_ = NULL;
		GomRepository* _tmp16_;
		GomRepository* _tmp17_;
		GomRepository* _tmp18_;
		GList* _tmp19_;
		GomAdapter* _tmp20_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp11_ = stdout;
		_tmp12_ = e;
		_tmp13_ = _tmp12_->message;
		fprintf (_tmp11_, "Error: %s\n", _tmp13_);
		_tmp16_ = yk_easy_open_sync ("/home/nar6du14/Projects/vala/gom/test/test.db", &_tmp15_, &_inner_error0_);
		_g_object_unref0 (adapter);
		adapter = _tmp15_;
		_tmp14_ = _tmp16_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_error_free0 (e);
			goto __finally0;
		}
		_tmp17_ = _tmp14_;
		_tmp14_ = NULL;
		_g_object_unref0 (repo);
		repo = _tmp17_;
		_tmp18_ = repo;
		_tmp19_ = ltypes;
		ltypes = NULL;
		gom_repository_automatic_migrate_sync (_tmp18_, (guint) 1, _tmp19_, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (_tmp14_);
			_g_error_free0 (e);
			goto __finally0;
		}
		_tmp20_ = adapter;
		gom_adapter_close_sync (_tmp20_, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (_tmp14_);
			_g_error_free0 (e);
			goto __finally0;
		}
		_g_object_unref0 (_tmp14_);
		_g_error_free0 (e);
		_g_object_unref0 (repo);
		_g_object_unref0 (adapter);
		(ltypes == NULL) ? NULL : (ltypes = (g_list_free (ltypes), NULL));
		_g_object_unref0 (tesla);
		_g_object_unref0 (monitor);
		return;
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (repo);
		_g_object_unref0 (adapter);
		(ltypes == NULL) ? NULL : (ltypes = (g_list_free (ltypes), NULL));
		_g_object_unref0 (tesla);
		_g_object_unref0 (monitor);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_g_object_unref0 (repo);
	_g_object_unref0 (adapter);
	(ltypes == NULL) ? NULL : (ltypes = (g_list_free (ltypes), NULL));
	_g_object_unref0 (tesla);
	_g_object_unref0 (monitor);
}

int
main (int argc,
      char ** argv)
{
	yk_main ();
	return 0;
}

