/* stack.c generated by valac 0.56.18, the Vala compiler
 * generated from stack.vala, do not modify */

#include <glib-object.h>
#include <glib.h>
#include <stdio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define FOO_TYPE_BAR (foo_bar_get_type ())
#define FOO_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FOO_TYPE_BAR, FooBar))
#define FOO_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FOO_TYPE_BAR, FooBarClass))
#define FOO_IS_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FOO_TYPE_BAR))
#define FOO_IS_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FOO_TYPE_BAR))
#define FOO_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FOO_TYPE_BAR, FooBarClass))

typedef struct _FooBar FooBar;
typedef struct _FooBarClass FooBarClass;
typedef struct _FooBarPrivate FooBarPrivate;
enum  {
	FOO_BAR_0_PROPERTY,
	FOO_BAR_NUM_PROPERTIES
};
static GParamSpec* foo_bar_properties[FOO_BAR_NUM_PROPERTIES];

struct _FooBar {
	GObject parent_instance;
	FooBarPrivate * priv;
};

struct _FooBarClass {
	GObjectClass parent_class;
	gint c_property;
};

static gpointer foo_bar_parent_class = NULL;

VALA_EXTERN GType foo_bar_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FooBar, g_object_unref)
VALA_EXTERN void foo_bar_c_method (FooBarClass* klass);
VALA_EXTERN FooBar* foo_bar_new (void);
VALA_EXTERN FooBar* foo_bar_construct (GType object_type);
static void foo_bar_finalize (GObject * obj);
static GType foo_bar_get_type_once (void);

void
foo_bar_c_method (FooBarClass* klass)
{
	FILE* _tmp0_;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "print something here\n");
}

FooBar*
foo_bar_construct (GType object_type)
{
	FooBar * self = NULL;
	self = (FooBar*) g_object_new (object_type, NULL);
	return self;
}

FooBar*
foo_bar_new (void)
{
	return foo_bar_construct (FOO_TYPE_BAR);
}

static void
foo_bar_class_init (FooBarClass * klass,
                    gpointer klass_data)
{
	foo_bar_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = foo_bar_finalize;
}

static void
foo_bar_instance_init (FooBar * self,
                       gpointer klass)
{
}

static void
foo_bar_finalize (GObject * obj)
{
	FooBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FOO_TYPE_BAR, FooBar);
	G_OBJECT_CLASS (foo_bar_parent_class)->finalize (obj);
}

static GType
foo_bar_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (FooBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) foo_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FooBar), 0, (GInstanceInitFunc) foo_bar_instance_init, NULL };
	GType foo_bar_type_id;
	foo_bar_type_id = g_type_register_static (G_TYPE_OBJECT, "FooBar", &g_define_type_info, 0);
	return foo_bar_type_id;
}

GType
foo_bar_get_type (void)
{
	static volatile gsize foo_bar_type_id__once = 0;
	if (g_once_init_enter (&foo_bar_type_id__once)) {
		GType foo_bar_type_id;
		foo_bar_type_id = foo_bar_get_type_once ();
		g_once_init_leave (&foo_bar_type_id__once, foo_bar_type_id);
	}
	return foo_bar_type_id__once;
}

